language: python

script: skip

deploy:
  provider: releases
  name: Version $TRAVIS_TAG
  api_key:
    secure: HsU23gonV9fcz8bnEI2r8enejnrPiLkpsdSHQXNdDm32YR3k7NlrQEj30RNydLmYFxhkvCabid4ZJndNeG78Y3EarKplAZd2ZIHFcxcYfmSIvCpUHkmXQQqWzg0IuramX5bJCVJEIaqzDM26ZdGGARrUQHBpxxDqCzk6lae4nEcAqey175bJJ+iRa9Y7zbre/apfn6Vy6ZDQwhTjcXaw2/ha76UiBAFqDupkyZ2DYf0OWsWEUsRUgngj84e4ekN7QGLOiK/w66NFOvDVrkx2Tn3tEtrNjoyQCs13MlF1lSDd31F7QpnVQZnTM6BQ3y+n74ysPJsy5Jt4ltZ7yHpquB0PNqusDCPvGVRaSochGoLiIk8lnp8ZKkimUlTvZXBhWnNjyDnjDPgJ6J1lDjhQ9koGMEHR2RlhPibZ6yEwxAt5Lbi0iM5Y3nrsh3tUxj03kls2iBZ5XdmON9bhBGMafCJUQ13UKQ0ibCr62BXDhSEI9fPRPH6CUuePPT8WdNfByQxayzkhdL2XImgxsyU4MSG0rOutgTIMLiKybvpqmeGZ60aK1exeTqjKbYebfW0JIhFxCebd+CIA4QHvUNXTX2oZImR97qlqKzBORBp9S+MiIcvu4P+u7yYKXzKrjAIseV7xTkAHejw1kFI8yzuXNdDUy9u3fHxaC8Yqvu1vTJo=
  on:
    tags: true
